[icons]
bluetooth = "\uf293"
bluetoothSlash = "\uf00b0"
wifi = "\uf0928"
wifiSlash = "\uf092f"
network = "\uf0318"
battery = "\uf240"
batteryCharging = "\uf0084"
cpu = "\uf4bc"
memory = "\uf035b"
gpu = "\uf0fb2"
disk = "\uf02ca"
arrowUpRight = "\uf062"
arrowDownRight = "\uf063"
arrowUpCircle = "\uf01b"
arrowDownCircle = "\uf01a"
clock = "\uf0954"
music = "\uf001"
play = "\uf04b"
pause = "\uf04c"
forward = "\uf051"
backward = ""
speaker = "\uf027"
speakerWave = "\uf028"
mic = "\uec1c"
micSlash = "\uf131"
appleLogo = "\uf179"
paperplane = "\uf01d8"
thermometer = "\uf02cb"
link = "\uf0337"
linkPlus = "\uf0338"
arrowClockwise = "\uf002d"
bolt = "\uf00e7"
grid = "\uf00a"
list = "\uf03a"
