[icons]
bluetooth = "󰂯"
bluetoothSlash = "󰂲"
wifi = "󰤨"
wifiSlash = "󰤭"
network = "󰲝"
battery = "󰁹"
batteryEmpty = "󰂃"
batteryQuarter = "󰁺"
batteryHalf = "󰁾"
batteryThreeQuarters = "󰂁"
batteryCharging = "󰂄"
cpu = "󰍛"
memory = "󰘚"
gpu = "󰢮"
disk = "󰋊"
arrowUpRight = "󰁝"
arrowDownRight = "󰁅"
arrowUpCircle = "󰁝"
arrowDownCircle = "󰁅"
clock = "󰥔"
music = "󰝚"
play = "󰐊"
pause = "󰏤"
forward = "󰒭"
backward = "󰒮"
speaker = "󰕮"
speakerWave = "󰕾"
mic = "󰍬"
micSlash = "󰍭"
appleLogo = "󰀵"
paperplane = "󰈆"
thermometer = "󰔏"
link = "󰌹"
linkPlus = "󰌺"
arrowClockwise = "󰑐"
bolt = "󰌪"
grid = "󰕰"
list = "󰝖"
bed = "󰒲"
laptop = "󰌢"
power = "⏻"
exit = "󰈆"
lock = "󰌾"
